---
title: "LB4L PCR Ss Standard Model"
author: "Will Hopper"
date: "`r Sys.Date()`"
output: 
  html_document:
    fig_caption: yes
    toc: true
    toc_depth: 2
    css: custom.css
params:
  inpar: FALSE
  model: FAM::LB4L_PCRss
  routine: testing
  pars: !r c("ER","LR","TR","F1","space")
  fixed: !r c(theta=.5,nFeat=100,nSim=1000,nList=15)    
---

```{r setup, cache=FALSE,echo=FALSE, warning=F, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE,fig.width=11,fig.height=7,cache=FALSE, 
               warning=F, message=FALSE, fig.align='center')
library(Hmisc) # Load before dplyr to prevent summarise getting masked
library(dplyr)
library(FAM)
library(reshape2)
library(whoppeR)
library(grid)
library(gridExtra)
library(ggplot2)
library(xtable)
```

```{r functions}
cueLabeller <- function(variable,value) {   
  cueNames <- list( 'Same Cue', 'Other Cue')
  groupNames <- list( 'Immediate', 'Delay') 
  if (variable=='cues') {
    return(cueNames[value])
  } else {
    return(groupNames[value])
  }
}

errFcn <- function(free, fixed, IVdata, jointData, fcn = LB4L_PCRss) {
  
  if (!paramBounds(c(free,fixed)) | anyNA(c(free,fixed))) {
    return(1000000)
  }
  
  preds <- fcn(free=free, fixed=fixed) %>% 
  joint <- left_join(obs,preds$JD, by = c("practice","other_type"))
  IV <- left_join(obs,preds$IV, by = c("practice","other_type","prac_score","final_score"))
  err <- binomialLL(obs=IV$acc,pred=IV$pred_acc ,N=fixed['nList']) +
         multinomialLL(obs=joint$acc,pred=joint$pred_acc, N = fixed['nList'])

  return(err)
}

paramBounds <- function(p) {

  probability_params <- c("ER","LR","TR","FR","space")
  prob_check <- any(p[names(p) %in% probability_params] <= 0, na.rm = TRUE) ||
                any(p[names(p) %in% probability_params] >= 1, na.rm = TRUE)
  if (any(prob_check)) {
    return(FALSE)
  } else {
    return(TRUE)
  }
}

minimization_routine <- function(model, erf = errFcn) {

  fit <- optimx(par = model$free[[j]],
                fn = erf,
                method="Nelder-Mead",
                itnmax=1000,
                control = list(maxit=1000,kkt=FALSE),
                fcn = model$obj, # passed to erf
                fixed = model$fixed, # passed to erf
                IVdata = model$IVdata[model$IVdata$subject == j,], # for erf
                jointData = model$jointData[model$jointData$subject == j,]) # for erf
  fit$subject = j
  return(fit)  
}

testing_routine <- function(model, erf = errFcn) {
  err <- erf(free = model$free[[j]], fixed = model$fixed, 
             IVdata = model$IVdata[model$IVdata$subject == j,],
             jointData = model$jointData[model$jointData$subject == j,])
  fit <- structure(data.frame(t(c(model$free[[j]], value = err,subject=j))),
                   details = NULL, maximize = NULL,
                   npar = length(model$free[[j]]), follow.on=NULL,
                   class = c("optimx", "data.frame"))
  return(fit)
}

```

```{r fetchData}
bad <- badSubs(LB4L_allSs)$removed
LB4L_allSs <- filter(LB4L_allSs, !(subject %in% bad))
uniqueSs <- unique(LB4L_allSs$subject)
LB4L_allSs$subject <- factor(LB4L_allSs$subject)
IVdata <- heirarchicalSummary(collapse = c("subject","group"),
                              hold =c("practice","other_type"),
                              rawData = cbind(filter(LB4L_allSs,list !=1) ,n=1),
                              prac_sd = sd(prac_score),
                              prac_score = mean(prac_score,na.rm=TRUE),
                              final_sd = sd(final_score),                            
                              final_score = mean(final_score),
                              n=sum(n))
jointData <- LB4L_joint(LB4L_allSs)
condData <- LB4L_conditional(LB4L_allSs)
```

```{r set_model}
if (!all(unlist(lapply(lapply(free,names), setequal, params$pars)))) {
  stop("Model specs in header don't match free parameters. Edit header or list of free parameters")
}

free <- replicate(length(unique(IVdata$subject)),
                  c(ER=.52,LR=.2,TR =.03, F1=.05,space=.03),
                  simplify = FALSE)

mname <- strsplit(as.character(params$model),"::")[[1]]
fname <- paste(mname[length(mname)],
               paste0(params$pars,collapse="_"),
               sep="_")
fpath <- file.path("data",paste(fname,'rds',sep='.'))
model <- list(free = free,
              fixed =  params$fixed,
              obj = eval(parse(text=params$model)),
              IVdata = IVdata$subject,
              jointData = jointData$subject)

if (params$routine =="minimize") {
  routine <- minimization_routine
} else {
  routine <- testing_routine
}
```


```{r load_or_fit}
if (!file.exists(fpath))  {
  
  if (params$inpar) {
    cluster <- tryDoParallelCluster(detectCores()-1)
  }

  if (params$inpar && cluster$success) {
    logfile <- tempfile("parlog", fileext = ".txt")
    message(paste("Log at", logfile))
    cat(paste('[',Sys.time(),']',"INIT parlog"),
        file=logfile, sep='\n')
    clusterExport(cluster$handle,c("accuracyErrorFcn", "RT_ErrorFcn","routine"))
    results <- foreach(j =unique(model$data$subject), .verbose=T,
                             .packages=c("optimx","PCR","whoppeR",
                                         "dplyr","FAM","reshape2","tidyr"))  %dopar% {
      sink(logfile, append=TRUE)
      cat(paste("Fitting subject", j,"\n"))
      results <- try(routine(model))
      sink()
      results
      }
    
    stopCluster(cluster$handle)
    cat(paste('[',Sys.time(),']',"Finished Fitting"),
        file=logfile,sep='\n')
  } else {
    
    results <- vector(mode='list', length =length(unique(model$data$subject)))
    for (j in unique(model$data$subject)) {
      message(paste("Fitting subject", j))
      results[[j]] <-  try(routine(model))
    }
  }
  
  saveRDS(results, file = fpath)  
} else {
  
  results <- readRDS(fpath)
}

```


```{r unlist_and_extract}
best_params <- lapply(results,function(x) {
  x <- as.vector(coef(x))
  names(x) <- params$pars
  return(x) }
  )

preds <- lapply(best_params, LB4L_PCRss, fixed = model$fixed)
IVpreds <- bind_rows(lapply(preds,`[[`,'IV'),.id="subject") %>%
  mutate(subject = factor(uniqueSs[as.numeric(subject)]),
         practice = factor(practice),
         other_type = factor(other_type,exclude=NULL)) %>%
  rename(pred_prac_score = prac_acc,
         pred_final_score = final_acc)
  
CDpreds <-  bind_rows(lapply(preds,`[[`,'CD'),.id="subject") %>%
  mutate(subject = factor(uniqueSs[as.numeric(subject)]),
         practice = factor(practice),
         other_type = factor(other_type,exclude=NULL),
         prac_score = factor(prac_score)) %>%
  rename(merged_prac_score = prac_score,
         pred_final_acc = final_acc)
JDpreds <-  bind_rows(lapply(preds,`[[`,'JD'),.id="subject") %>%
  mutate(subject = factor(uniqueSs[as.numeric(subject)]),
         practice = factor(practice),
         other_type = factor(other_type,exclude=NULL),
         prac_acc  = factor(prac_acc)) %>%
  rename(merged_prac_score = prac_acc,
         pred_acc = acc)
```

## Model Specs
```{r modelInfo,results='asis'}
print(xtable(t(as.matrix(results$par)), digits=3,
             caption = paste("Starting Free Parameters")),
      type = "html", include.rownames=FALSE, caption.placement="top")
print(xtable(t(as.matrix(results$fixed)), digits=3,
             caption = paste("Fixed Parameters")),
      type = "html", include.rownames=FALSE, caption.placement="top")
```

```{r IVdata}
IVdata_all <- IVdata$subject %>% 
   mutate(type = "model") %>%
   group_by(subject) %>%
   mutate(prac_score = replace(prac_score, !is.na(prac_score), 
                             preds$prac[subject[1]]),
          final_score = replace(final_score, practice=='C' & other_type!='T',
                              preds$C[subject[1]]),
          final_score = replace(final_score, practice=='S', preds$S[subject[1]]),
          final_score = replace(final_score, practice=='T' & other_type!='C',
                              preds$`T`[subject[1]]),
          final_score = replace(final_score, practice=='C' & other_type=='T',
                              preds$CT[subject[1]])) %>% 
   rbind(cbind(IVdata$subject,type="real")) %>% 
   melt(id.vars = c("subject","group", "practice",
                    "other_type","type"),
        measure.vars = c("prac_score","final_score"),
        value.name = 'pc') %>%
   mutate(timepoint = factor(ifelse(grepl("prac",variable,fixed=TRUE),
                                    1, 
                                    ifelse(grepl("delay",group,fixed=TRUE), 3,2))))

IVdata_grouped <- IVdata_all %>%
  group_by(group,practice,other_type,
           type, timepoint, variable) %>%
  summarise(pc= mean(pc)) %>%
    mutate(group_del_to_imm = replace(group,
                                      which(group=='delay' & timepoint ==3),
                                      'immediate'),
           group_imm_to_del = replace(group,
                                      which(group=='immediate' & timepoint ==2),
                                      'delay'))  
  
```

```{r condData}
condData_all <- condData$subject %>%
  mutate(type='model') %>% 
  group_by(subject) %>%
  mutate(final_acc = replace(final_acc, practice=='C' & merged_prac_score==1,
                            preds$CTplus[subject[1]]),
         final_acc = replace(final_acc, practice=='C' & merged_prac_score==0,
                            preds$CTneg[subject[1]]),
         final_acc = replace(final_acc, practice=='T' & merged_prac_score==1,
                            preds$Tplus[subject[1]]),
         final_acc = replace(final_acc, practice=='T' & merged_prac_score==0,
                            preds$Tneg[subject[1]])) %>%
  rbind(cbind(condData$subject,type="real")) %>%
  filter((practice =='T' & !other_type %in% 'C') | 
         (practice =='C' & other_type %in% 'T'))

  condData_grouped <-condData_all %>%
    group_by(group,practice, other_type, prac_score,
             other_prac_acc,merged_prac_score,type) %>%
    summarise(weighted_final_acc=weighted.mean(final_acc, count),
              final_acc= mean(final_acc,na.rm=TRUE),
              missing=length(count[count==0])/n(), #length(count),
              count = sum(count),
              upper = qbinom(sqrt(.025), count,final_acc,lower.tail=F)/count,
              lower = qbinom(sqrt(.025), count,final_acc,lower.tail=T)/count)
```
   
```{r jointData}   
jointData_all <- jointData$subject %>% 
   mutate(type = "model") %>%
   group_by(subject) %>%
   mutate(acc = replace(acc, practice=='C' & other_type=='T' ,
                             c(preds$CT_not_prac_not_final[subject[1]],
                               preds$CT_not_prac_final[subject[1]],
                               preds$CT_prac_not_final[subject[1]],
                               preds$CT_prac_final[subject[1]])),
          acc = replace(acc, practice=='T' & is.na(other_type),
                             c(preds$T_not_prac_not_final[subject[1]],
                               preds$T_not_prac_final[subject[1]],
                               preds$T_prac_not_final[subject[1]],
                               preds$T_prac_final[subject[1]]))) %>%                  
   rbind(cbind(jointData$subject,type="real"))  %>%
   filter(final_score %in% 0:1, !is.na(merged_prac_score)) %>% 
    mutate(prac = factor(merged_prac_score,labels = c("inc","cor")),
           final = factor(final_score,labels = c("inc","cor")),
           xaxis = interaction(practice,prac,final))
  
  jointData_grouped <- jointData_all%>%
    group_by(group, practice, other_type, prac, final,xaxis,type) %>%
    summarise(acc = mean(acc))
```

## Subject Fits
```{r subjectPlots, results='asis'}

for (i in unique(IVdata_all$subject)) {
  
  cat('<h4 class="subid"> Subject',i,'Results </h4>')
  print(xtable(data.frame(Subject = i,
                          Group =IVdata_all$group[IVdata$subject==i][1],
                          select(fits[as.numeric(i),],-subject)),
                 digits=3, caption = paste("Best Parameters")),
          type = "html", include.rownames=FALSE, caption.placement="top")  
  IVplot <- ggplot(data= filter(IVdata_all, subject==i, is.finite(pc)),
                   aes(x=timepoint, y=pc, shape=type,
                       color = strSort(interaction(practice,factor(other_type,exclude=NULL))),
                       group = strSort(interaction(type, practice,factor(other_type,exclude=NULL))))) +
        geom_point(size=3) +    
        geom_line(size=.75) + 
        scale_x_discrete("Test",expand=c(0,.25),labels=c("Practice","Final")) + 
        scale_color_discrete("Condition",labels = c("2 Cues\n1=Tested & 2=Unpracticed",
                                                    "1 Cue, No Practice",
                                                    "1 Cue, Restudied",
                                                    "1 Cue, Tested")) +
        scale_shape_discrete("Type", labels=c("real" = "Obs. Data",
                                              "model" = "PCR Model")) +
        scale_y_continuous("Final Test Accuracy",limit=0:1) +
        theme(legend.key.height=unit(2,"line")) + 
        ggtitle('Test Accuracy')
  
  condPlot <- ggplot(filter(condData_all,subject ==i,type=='real'),
                    aes(x=other_type, y= final_acc,
                        fill=merged_prac_score,ymax=1)) +
        geom_bar(position='dodge',stat="identity") +
        geom_point(shape= 19, size = 3, position = position_dodge(width=0.9),
                   data = filter(condData_all,subject ==i,type=='model')) +
        # label n observations in each cell
        geom_text(aes(y=-.025,label =count, group=merged_prac_score),
                  position = position_dodge(width=0.9)) +
        scale_fill_brewer("Practice\nAccuracy",
                          breaks=c(0,1),
                          labels=c("Incorrect", "Correct"),
                          palette="Set1") +
        scale_x_discrete("Final Test Cue",
                         limits=c(NA,'T'),labels=c("Practiced","Unpracticed")) +
        scale_y_continuous("Final Test Accuracy",expand=c(0,.025)) +
        theme_larger() +
        ggtitle('Conditional Final Test Accuracy')

  
  jointPlot <- ggplot(data = filter(ungroup(jointData_all), subject==i) %>%
                        mutate(cues = factor(ifelse(grepl("C.",xaxis),2,1))),
                      aes(x=interaction(prac,final), y= acc, color = type)) +
    geom_point(size= 4, position = position_dodge(width=.15)) +
    facet_grid(~cues,labeller = cueLabeller) + 
    scale_x_discrete(labels = c("cor.cor" =" + / +",
                                "cor.inc"  =  "+ /-",
                                "inc.cor"  = "- / +",
                                "inc.inc" = "- / -."),
                     name = "Practice / Final Accuracy") +
    scale_color_discrete("Type", labels=c("real" = "Obs. Data",
                                          "model" = "PCR Model")) +
    scale_y_continuous("Proportion",limit=0:1) +
    theme(axis.text.x = element_text(size=rel(1.5))) +
    ggtitle("Joint Accuracy Probabilities")
  
  grid.arrange(IVplot, condPlot ,ncol=2,nrow=1)
  print(jointPlot)

}
```

## Average Fits 
```{r groupPlots,results='asis',fig.height=11}
IVplot_grouped <- IVplot %+%  filter(IVdata_grouped,is.finite(pc)) + 
    geom_line(aes(group = strSort(interaction(type, group_del_to_imm,
                                              practice, factor(other_type,exclude=NULL)))),
              size=.75)

condPlot_grouped <- ggplot(filter(condData_grouped, type=="real"),
                           aes(x=other_type, y= final_acc,
                               fill=merged_prac_score,ymax=1)) +
  geom_bar(position='dodge',stat="identity") +
  geom_point(shape= 19, size = 3, position = position_dodge(width=0.9),
             data = filter(condData_grouped, type=='model'))  +  
  geom_errorbar(aes(ymax =upper, ymin=lower),
                position=position_dodge(width=.9), width=0.2,
                data= condData_grouped) +
        # label n observations in each cell
  geom_text(aes(y=-.025,label =count, group=merged_prac_score),
            position = position_dodge(width=0.9)) +
    facet_grid(. ~ group,
               labeller=function(...) {
                 return(c("Immediate","Delayed"))
               }) + 
    scale_fill_brewer("Practice\nAccuracy",
                      breaks=c(0,1),
                      labels=c("Incorrect", "Correct"),
                      palette="Set1") +
    scale_x_discrete("Final Test Cue",
                     limits=c(NA,'T'),labels=c("Practiced","Unpracticed")) +
    scale_y_continuous("Final Test Accuracy",expand=c(0,.025)) +
    ggtitle('Conditional Final Test Accuracy') 

  jointPlot_grouped <- jointPlot %+% 
    mutate(ungroup(jointData_grouped),
           cues = factor(ifelse(practice == "C",2,1))) + 
    facet_grid(group ~ cues,labeller = cueLabeller)

avg_res <- IVdata_all %>% group_by(subject) %>% 
  slice(1) %>% 
  ungroup() %>% select(group) %>%
  cbind(fits) %>%
  group_by(group) %>% 
  summarise_each(funs(mean))

print(xtable(as.matrix(avg_res[1:which(names(avg_res)=='value')]),
             digits=3,
             caption = paste("Average Parameters")),
        type = "html", include.rownames=FALSE, caption.placement="top")
print(IVplot_grouped)
print(condPlot_grouped)
print(jointPlot_grouped)

```

```{r simpler_averages,eval=FALSE}
simplerIVPlot <- ggplot(data = filter(IVdata_grouped, timepoint != 1, is.finite(pc)),
                        aes(x = group, y = pc, ymax=.85, ymin=.15,
                            shape=type,
                            color = strSort(interaction(practice,factor(other_type,exclude=NULL))),
                            group = strSort(interaction(type, practice,factor(other_type,exclude=NULL))))) +
    geom_point(size=3.25) + 
    geom_line(size=.75) +
#     geom_errorbar(aes(ymax = pc + final_sd/sqrt(groupsize),
#                       ymin = pc - final_sd/sqrt(groupsize)),
#                   width = .075) + 
    scale_color_discrete("Condition",
                         breaks = c("C.T","C.NA","NA.S","NA.T"),
                         labels = c(C.T = "Other Cue", C.NA = "Baseline",
                                    NA.S  = "Restudy", NA.T = "Same Cue")) + 
    scale_x_discrete("Group",expand=c(0,.25),
                     labels=c("Immediate","Delay")) + 
    ylab("Final Test Accuracy") + 
    theme(legend.key.height=unit(2,"line")) + 
    ggtitle('Cued Recall Accuracy')   + 
    theme_larger()
  
simplerCondPlot <-condPlot_grouped + 
  scale_x_discrete("Final Test Cue", limits=c(NA,'T'),
                   labels=c("Same Cue","Other Cue")) +
  theme_larger()
simplerjointPlot <- jointPlot_grouped + theme_larger()
  
```  
